include(${CMAKE_CURRENT_LIST_DIR}/asrc_unit_tests/asrc_unit_tests.cmake)
if(${CMAKE_SYSTEM_NAME} STREQUAL XCORE_XS3A)
    include(${CMAKE_CURRENT_LIST_DIR}/asr/asr.cmake)
    include(${CMAKE_CURRENT_LIST_DIR}/ffd_gpio/gpio.cmake)
    include(${CMAKE_CURRENT_LIST_DIR}/ffd_low_power_audio_buffer/low_power_audio_buffer.cmake)
    include(${CMAKE_CURRENT_LIST_DIR}/pipeline/pipeline.cmake)
endif()
