// Copyright 2023 XMOS LIMITED.
// This Software is subject to the terms of the XCORE VocalFusion Licence.
/* Autogenerated by sw_pll_sim.py using command:
   /Users/ed/sandboxes/sw_xvf3800/lib_sw_pll/python/sw_pll/pll_calc.py -i 24.0  -a -m 90 -t 12.288 -p 6.0 -e 5 -r --fracmin 0.49 --fracmax 0.81 --header
   Picked output solution #83
   F: 154
   R: 1
   f: 56
   p: 87
   OD: 1
   ACD: 18
   Output freq: 12287978.0
   VCO freq: 1867770000.0 */

#define APP_PLL_CTL_REG  	0x08809A01
#define APP_PLL_DIV_REG  	0x80000012
#define APP_PLL_FRAC_REG  	0x80003857
