# The following patterns are to be excluded from the documentation build
documents/shared
modules/core/modules/legacy_compat
modules/core/modules/otpinfo
modules/core/modules/random
modules/core/modules/trycatch
modules/rtos/modules/FreeRTOS
modules/io/modules/xud
modules/io/doc/substitutions.rst
modules/sample_rate_conversion
modules/lib_qspi_fast_read
modules/xscope_fileio
modules/sw_pll
modules/xua
modules/voice

sln_voice_venv
**/.venv
test
xmos_cmake_toolchain
build_*
modules/*/build
modules/*/build_*
modules/*/index*
modules/*/doc/index*
# modules/*/doc/shared/legal.rst
modules/*/modules/*/index*
**/*.md
**/*.ipynb
**CHANGELOG*
**LICENSE*
**README*
