
include(${CMAKE_CURRENT_LIST_DIR}/dac/dac.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/XCORE-AI-EXPLORER/XCORE-AI-EXPLORER.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/XCORE-AI-EXPLORER_EXT/XCORE-AI-EXPLORER.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/XK_VOICE_L71/XK_VOICE_L71.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/XK_VOICE_L71_EXT/XK_VOICE_L71.cmake)
